version: "3.9"

services:
  mcp-server-itsm:
    build: .
    container_name: mcp-server-itsm
    # 加载 .env 中的 IVANTI_* 配置
    env_file:
      - .env
    # 如果你希望以 HTTP 模式启动（推荐生产部署），可映射端口
    ports:
      - "8000:8000"
    # 依启动参数选择 transport：
    # --transport stdio               : 标准流通信模式（无需映射端口）
    # --transport streamable-http     : HTTP/长连接模式，映射端口后客户端可通过网络调用
    command: >
      uv run src/mcp_server_itsm/server.py
      --transport streamable-http
      --host 0.0.0.0
      --port 8000

# 不再需要数据库或其他服务
