# docker-compose.yml
version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mcp-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: mcp_demo
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3307:3306"   # 宿主机 3307 → 容器内 3306

  server:
    build: .
    container_name: mcp-server
    depends_on:
      - db
    env_file:
      - .env
    environment:
      # —— MySQL 连接信息（与 server.py 中默认保持一致，可通过 .env 覆盖）——
      DASHSCOPE_API_KEY: ${DASHSCOPE_API_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "8000:8000"

volumes:
  db_data:

